language: ruby
services:
- docker
before_install:
- docker-compose build
- docker-compose run web rake db:create
- docker-compose run web rake db:migrate
- gem install bundler -v 2.1.4
rvm:
- 2.5
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push $DOCKER_USERNAME/blog_app_web